AllCops:
  TargetRubyVersion: 2.2


Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false


Metrics/ClassLength:
  Max: 500

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ModuleLength:
  Max: 500

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Alias:
  Enabled: false

Style/CommentIndentation:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/IndentationConsistency:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/OptionHash:
 Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpaceAroundBlockParameters:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingBlankLines:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/WordArray:
  Enabled: false