Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IndentationConsistency:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false